<?php

CRM_Core_BAO_OptionValue::ensureOptionValueExists([
  'option_group_id' => 'cg_extend_objects',
  'name' => 'civicrm_custom_field',
  'label' => ts('Custom Field'),
  'value' => 'CustomField',
]);

return [
  [
    'name' => 'SecurePayFields',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Custom_Fields',
        'title' => 'Secure Pay Mapping',
        'extends' => 'CustomField',
        'extends_entity_column_value' => NULL,
        'style' => 'Inline',
        'collapse_display' => FALSE,
        'help_pre' => '<p>This allows a custom field to be designated as an incoming Secure Pay field. The name in the field is the name in the key that comes in from Secure pay</p>',
        'help_post' => '',
        'weight' => 2,
        'is_active' => TRUE,
        'is_multiple' => FALSE,
        'min_multiple' => NULL,
        'max_multiple' => NULL,
        'collapse_adv_display' => TRUE,
        'created_date' => '2022-07-04 03:51:19',
        'is_reserved' => FALSE,
        'is_public' => TRUE,
        'icon' => '',
        'extends_entity_column_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SecurePayFields_CustomField_Secure_pay_field',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Custom_Fields',
        'name' => 'Secure_pay_field',
        'label' => 'Secure pay field',
        'data_type' => 'String',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => 'The name of a the field coming in from a secure pay request',
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'secure_pay_field_7',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
        'Custom_Fields.Secure_pay_field' => NULL,
      ],
    ],
  ],
];
