<?php
return [
  [
    'name' => 'SavedSearch_SecurePay',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'SecurePay',
        'label' => 'SecurePay',
        'form_values' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'Securepay',
        'api_params' => [
          'version' => 4,
          'select' => [
            'order_id',
            'contribution_id',
            'receive_date',
            'amount',
            'order_status_id:label',
            'processing_status_id:label',
            'first_name',
            'last_name',
            'is_test',
            'email',
            'street_address',
            'supplemental_address_1',
            'postal_code',
            'city',
            'state',
            'modified_date',
            'created_date',
            'data',
            'id',
          ],
          'orderBy' => [],
          'where' => [
            [
              'OR',
              [
                [
                  'is_test',
                  '=',
                  TRUE,
                ],
                [
                  'is_test',
                  '=',
                  FALSE,
                ],
              ],
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
        'mapping_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_SecurePay_SearchDisplay_SecurePay_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'SecurePay_Table_1',
        'label' => 'SecurePay Messages',
        'saved_search_id.name' => 'SecurePay',
        'type' => 'table',
        'settings' => [
          'actions' => TRUE,
          'limit' => 50,
          'classes' => [
            'table',
            'table-striped',
          ],
          'pager' => [
            'show_count' => TRUE,
            'expose_limit' => TRUE,
          ],
          'sort' => [],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'order_id',
              'dataType' => 'String',
              'label' => 'order_id',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'contribution_id',
              'dataType' => 'Integer',
              'label' => 'contribution_id',
              'sortable' => TRUE,
              'link' => [
                'path' => '/civicrm/contact/view/contribution?reset=1&action=view&context=contribution&id=[contribution_id]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => 'crm-popup',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'receive_date',
              'dataType' => 'Timestamp',
              'label' => 'Date Received',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'amount',
              'dataType' => 'Money',
              'label' => 'Total Amount',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'order_status_id:label',
              'dataType' => 'Integer',
              'label' => 'Order Status',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'processing_status_id:label',
              'dataType' => 'Integer',
              'label' => 'Processing Status',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'first_name',
              'dataType' => 'String',
              'label' => 'First Name',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'last_name',
              'dataType' => 'String',
              'label' => 'Last Name',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_test',
              'dataType' => 'Boolean',
              'label' => 'Test',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'email',
              'dataType' => 'String',
              'label' => 'Email',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'street_address',
              'dataType' => 'String',
              'label' => 'Street Address',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'supplemental_address_1',
              'dataType' => 'String',
              'label' => 'Supplemental Address 1',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'postal_code',
              'dataType' => 'String',
              'label' => 'Postal Code',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'city',
              'dataType' => 'String',
              'label' => 'City',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'state',
              'dataType' => 'String',
              'label' => 'State',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'modified_date',
              'dataType' => 'Timestamp',
              'label' => 'Modified Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'created_date',
              'dataType' => 'Timestamp',
              'label' => 'Created Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'data',
              'dataType' => 'Text',
              'label' => 'Data',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => 'id',
              'sortable' => TRUE,
            ],
          ],
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
